---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: karpenter-psp-controlplane-20240327163624269700000001
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: psp-controlplane
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: psp-controlplane
  tags:
    managed-by: karpenter
